[jenkins_server]
# Replace <JENKINS-IP> with your CI/CD server public IP
13.127.22.145 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/webapp.pem

[k3s_master]
# Replace <MASTER-IP> with your Kubernetes Master server public IP
13.232.161.173 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/webapp.pem

[k3s_workers]
# Replace <WORKER-IP> with your Kubernetes Worker server public IP
# You can add multiple workers by listing them on new lines
52.66.204.203 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/webapp.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
