[ec2_servers]
# Replace this with the public IP or DNS of your AWS EC2 instance
# Example: ec2-user@198.51.100.1
43.204.236.46 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/webapp.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
